[package]
name = "langcities-dc"
version.workspace = true
authors.workspace = true
edition.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true

[features]
default = ["sqlite"]

sqlite = ["sea-orm/sqlx-sqlite"]
postgres = ["sea-orm/sqlx-postgres"]
mysql = ["sea-orm/sqlx-mysql"]

dev = ["sea-orm/debug-print"]

[dependencies]
axum = { version = "0.8.9", features = ["macros"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
langcities-common = { path = "../langcities-common", features = ["axum"] }
langcities-common-db = { path = "../langcities-common-db" }
langcities-common-server = { path = "../langcities-common-server" }
langcities-config = { path = "../langcities-config" }
langcities-jwt = { path = "../langcities-jwt", features = ["axum"] }
serde = { version = "1.0.229", features = ["derive"] }
figment = { version = "0.10.19", features = ["env", "json"] }
clap = { version = "4.6.6", features = ["derive"] }
serde_json = "1.0.151"
utoipa = { version = "5.5.0", features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
time = "0.3.55"
axum-extra = { version = "0.12.6", features = ["typed-header"] }
chrono = { version = "0.4.45", features = ["serde"] }

[dependencies.log]
version = "0.4.33"
features = ["std", "serde"]

[dependencies.sea-orm]
version = "^2.0.2"
default-features = false
features = ["macros", "runtime-tokio-rustls", "with-chrono"]

[dependencies.tokio]
version = "1.53.1"
features = ["full"]
