[package]
name = "langcities-common-db"
version.workspace = true
authors.workspace = true
edition.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
log = "0.4.33"
serde = { version = "1.0.229", features = ["derive"] }
langcities-common = { path = "../langcities-common" }
langcities-config = { path = "../langcities-config"}
figment = { version = "0.10.19", features = ["env"] }
clap = { version = "4.6.6", features = ["string"] }
sea-orm = { version = "2.0.2", default-features = false, features = ["macros", "runtime-tokio-rustls", "with-chrono"] }
