[package]
name = "tree-sitter-lcdcdsl"
description = "Parser for LangCities Domain Specific Language. Expressions in this DSL are used to generate values for LangCities Dictionaries."
version = "0.1.0"
authors = ["RenoirTan <renoirtan2005@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "lcdcdsl"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/renoirtan/langcities"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.11"
