[package]
name = "langcities-lcdcdsl"
version.workspace = true
authors.workspace = true
edition.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
langcities-common = { path = "../langcities-common" }
serde = { version = "1.0.229", features = ["derive"] }
