/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 19
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 2

enum ts_symbol_identifiers {
  sym_expression_sep = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_PLUS = 4,
  anon_sym_COMMA = 5,
  sym_identifier = 6,
  sym_unquoted_string_literal = 7,
  sym_dquoted_string_literal = 8,
  sym_squoted_string_literal = 9,
  sym_source_file = 10,
  sym_multi_expression = 11,
  sym_expression = 12,
  sym_parenthesis_expression = 13,
  sym_binary_expression = 14,
  sym_add_expression = 15,
  sym_function_call = 16,
  sym_string_literal = 17,
  aux_sym_multi_expression_repeat1 = 18,
  aux_sym_multi_expression_repeat2 = 19,
  aux_sym_function_call_repeat1 = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_expression_sep] = "expression_sep",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PLUS] = "+",
  [anon_sym_COMMA] = ",",
  [sym_identifier] = "identifier",
  [sym_unquoted_string_literal] = "unquoted_string_literal",
  [sym_dquoted_string_literal] = "dquoted_string_literal",
  [sym_squoted_string_literal] = "squoted_string_literal",
  [sym_source_file] = "source_file",
  [sym_multi_expression] = "multi_expression",
  [sym_expression] = "expression",
  [sym_parenthesis_expression] = "parenthesis_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_add_expression] = "add_expression",
  [sym_function_call] = "function_call",
  [sym_string_literal] = "string_literal",
  [aux_sym_multi_expression_repeat1] = "multi_expression_repeat1",
  [aux_sym_multi_expression_repeat2] = "multi_expression_repeat2",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_expression_sep] = sym_expression_sep,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_identifier] = sym_identifier,
  [sym_unquoted_string_literal] = sym_unquoted_string_literal,
  [sym_dquoted_string_literal] = sym_dquoted_string_literal,
  [sym_squoted_string_literal] = sym_squoted_string_literal,
  [sym_source_file] = sym_source_file,
  [sym_multi_expression] = sym_multi_expression,
  [sym_expression] = sym_expression,
  [sym_parenthesis_expression] = sym_parenthesis_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_add_expression] = sym_add_expression,
  [sym_function_call] = sym_function_call,
  [sym_string_literal] = sym_string_literal,
  [aux_sym_multi_expression_repeat1] = aux_sym_multi_expression_repeat1,
  [aux_sym_multi_expression_repeat2] = aux_sym_multi_expression_repeat2,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_sep] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_dquoted_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_squoted_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_multi_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_parenthesis_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_add_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [aux_sym_multi_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multi_expression_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_first = 1,
  field_others = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_first] = "first",
  [field_others] = "others",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_first, 0},
  [1] =
    {field_first, 0},
    {field_others, 1, .inherited = true},
  [3] =
    {field_first, 1},
  [4] =
    {field_others, 1},
  [5] =
    {field_others, 0, .inherited = true},
    {field_others, 1, .inherited = true},
  [7] =
    {field_first, 1},
    {field_others, 2, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 8,
  [11] = 11,
  [12] = 9,
  [13] = 11,
  [14] = 14,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 14,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 25,
  [29] = 24,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 38,
  [40] = 31,
  [41] = 33,
  [42] = 42,
  [43] = 42,
  [44] = 44,
  [45] = 34,
  [46] = 46,
  [47] = 32,
  [48] = 36,
  [49] = 46,
  [50] = 44,
  [51] = 51,
  [52] = 51,
  [53] = 53,
  [54] = 53,
  [55] = 55,
  [56] = 56,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_expression,
  sym_string_literal,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_expression] = {.index = 0, .length = 5},
  [sym_string_literal] = {.index = 5, .length = 3},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_binary_expression,
    sym_function_call,
    sym_identifier,
    sym_parenthesis_expression,
    sym_string_literal,
  [5] =
    sym_dquoted_string_literal,
    sym_squoted_string_literal,
    sym_unquoted_string_literal,
};

static const TSCharacterRange sym_unquoted_string_literal_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '#'}, {'%', '&'}, {'*', '*'}, {'-', 'z'}, {'|', '|'},
  {'~', 0x17e}, {0x180, 0x2129}, {0x212b, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '"', 1,
        '$', 4,
        '\'', 2,
        '(', 11,
        ')', 12,
        '+', 13,
        ',', 14,
        '\\', 3,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"' ||
          lookahead == '$' ||
          ('\'' <= lookahead && lookahead <= ')') ||
          lookahead == '+' ||
          lookahead == ',' ||
          lookahead == '\\' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(19);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(1);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(2);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '\n', 10,
        '\r', 10,
        '"', 1,
        '$', 4,
        '\'', 2,
        '(', 11,
        '+', 13,
        '\\', 3,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '+' &&
          lookahead != ',' &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(19);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_expression_sep);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '\r') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == '@') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == '@') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_unquoted_string_literal);
      if (lookahead == '\\') ADVANCE(3);
      if ((!eof && set_contains(sym_unquoted_string_literal_character_set_1, 11, lookahead))) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_dquoted_string_literal);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_squoted_string_literal);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_unquoted_string_literal] = ACTIONS(1),
    [sym_dquoted_string_literal] = ACTIONS(1),
    [sym_squoted_string_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(55),
    [sym_multi_expression] = STATE(56),
    [sym_expression] = STATE(22),
    [sym_parenthesis_expression] = STATE(31),
    [sym_binary_expression] = STATE(31),
    [sym_add_expression] = STATE(33),
    [sym_function_call] = STATE(31),
    [sym_string_literal] = STATE(31),
    [aux_sym_multi_expression_repeat1] = STATE(6),
    [sym_expression_sep] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_unquoted_string_literal] = ACTIONS(9),
    [sym_dquoted_string_literal] = ACTIONS(9),
    [sym_squoted_string_literal] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_expression] = STATE(37),
    [sym_parenthesis_expression] = STATE(31),
    [sym_binary_expression] = STATE(31),
    [sym_add_expression] = STATE(33),
    [sym_function_call] = STATE(31),
    [sym_string_literal] = STATE(31),
    [aux_sym_multi_expression_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_expression_sep] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_unquoted_string_literal] = ACTIONS(9),
    [sym_dquoted_string_literal] = ACTIONS(9),
    [sym_squoted_string_literal] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym_expression] = STATE(37),
    [sym_parenthesis_expression] = STATE(31),
    [sym_binary_expression] = STATE(31),
    [sym_add_expression] = STATE(33),
    [sym_function_call] = STATE(31),
    [sym_string_literal] = STATE(31),
    [aux_sym_multi_expression_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_expression_sep] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_unquoted_string_literal] = ACTIONS(9),
    [sym_dquoted_string_literal] = ACTIONS(9),
    [sym_squoted_string_literal] = ACTIONS(9),
  },
  [STATE(4)] = {
    [sym_expression] = STATE(37),
    [sym_parenthesis_expression] = STATE(31),
    [sym_binary_expression] = STATE(31),
    [sym_add_expression] = STATE(33),
    [sym_function_call] = STATE(31),
    [sym_string_literal] = STATE(31),
    [aux_sym_multi_expression_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_expression_sep] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_unquoted_string_literal] = ACTIONS(9),
    [sym_dquoted_string_literal] = ACTIONS(9),
    [sym_squoted_string_literal] = ACTIONS(9),
  },
  [STATE(5)] = {
    [sym_expression] = STATE(37),
    [sym_parenthesis_expression] = STATE(31),
    [sym_binary_expression] = STATE(31),
    [sym_add_expression] = STATE(33),
    [sym_function_call] = STATE(31),
    [sym_string_literal] = STATE(31),
    [aux_sym_multi_expression_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_expression_sep] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_unquoted_string_literal] = ACTIONS(9),
    [sym_dquoted_string_literal] = ACTIONS(9),
    [sym_squoted_string_literal] = ACTIONS(9),
  },
  [STATE(6)] = {
    [sym_expression] = STATE(21),
    [sym_parenthesis_expression] = STATE(31),
    [sym_binary_expression] = STATE(31),
    [sym_add_expression] = STATE(33),
    [sym_function_call] = STATE(31),
    [sym_string_literal] = STATE(31),
    [aux_sym_multi_expression_repeat1] = STATE(20),
    [sym_expression_sep] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_unquoted_string_literal] = ACTIONS(9),
    [sym_dquoted_string_literal] = ACTIONS(9),
    [sym_squoted_string_literal] = ACTIONS(9),
  },
  [STATE(7)] = {
    [sym_expression] = STATE(37),
    [sym_parenthesis_expression] = STATE(31),
    [sym_binary_expression] = STATE(31),
    [sym_add_expression] = STATE(33),
    [sym_function_call] = STATE(31),
    [sym_string_literal] = STATE(31),
    [aux_sym_multi_expression_repeat1] = STATE(20),
    [sym_expression_sep] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_unquoted_string_literal] = ACTIONS(9),
    [sym_dquoted_string_literal] = ACTIONS(9),
    [sym_squoted_string_literal] = ACTIONS(9),
  },
  [STATE(8)] = {
    [sym_expression] = STATE(30),
    [sym_parenthesis_expression] = STATE(40),
    [sym_binary_expression] = STATE(40),
    [sym_add_expression] = STATE(41),
    [sym_function_call] = STATE(40),
    [sym_string_literal] = STATE(40),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [sym_unquoted_string_literal] = ACTIONS(29),
    [sym_dquoted_string_literal] = ACTIONS(29),
    [sym_squoted_string_literal] = ACTIONS(29),
  },
  [STATE(9)] = {
    [sym_expression] = STATE(25),
    [sym_parenthesis_expression] = STATE(40),
    [sym_binary_expression] = STATE(40),
    [sym_add_expression] = STATE(41),
    [sym_function_call] = STATE(40),
    [sym_string_literal] = STATE(40),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(31),
    [sym_identifier] = ACTIONS(27),
    [sym_unquoted_string_literal] = ACTIONS(29),
    [sym_dquoted_string_literal] = ACTIONS(29),
    [sym_squoted_string_literal] = ACTIONS(29),
  },
  [STATE(10)] = {
    [sym_expression] = STATE(30),
    [sym_parenthesis_expression] = STATE(40),
    [sym_binary_expression] = STATE(40),
    [sym_add_expression] = STATE(41),
    [sym_function_call] = STATE(40),
    [sym_string_literal] = STATE(40),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(33),
    [sym_identifier] = ACTIONS(27),
    [sym_unquoted_string_literal] = ACTIONS(29),
    [sym_dquoted_string_literal] = ACTIONS(29),
    [sym_squoted_string_literal] = ACTIONS(29),
  },
  [STATE(11)] = {
    [sym_expression] = STATE(30),
    [sym_parenthesis_expression] = STATE(40),
    [sym_binary_expression] = STATE(40),
    [sym_add_expression] = STATE(41),
    [sym_function_call] = STATE(40),
    [sym_string_literal] = STATE(40),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(35),
    [sym_identifier] = ACTIONS(27),
    [sym_unquoted_string_literal] = ACTIONS(29),
    [sym_dquoted_string_literal] = ACTIONS(29),
    [sym_squoted_string_literal] = ACTIONS(29),
  },
  [STATE(12)] = {
    [sym_expression] = STATE(28),
    [sym_parenthesis_expression] = STATE(40),
    [sym_binary_expression] = STATE(40),
    [sym_add_expression] = STATE(41),
    [sym_function_call] = STATE(40),
    [sym_string_literal] = STATE(40),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(37),
    [sym_identifier] = ACTIONS(27),
    [sym_unquoted_string_literal] = ACTIONS(29),
    [sym_dquoted_string_literal] = ACTIONS(29),
    [sym_squoted_string_literal] = ACTIONS(29),
  },
  [STATE(13)] = {
    [sym_expression] = STATE(30),
    [sym_parenthesis_expression] = STATE(40),
    [sym_binary_expression] = STATE(40),
    [sym_add_expression] = STATE(41),
    [sym_function_call] = STATE(40),
    [sym_string_literal] = STATE(40),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(39),
    [sym_identifier] = ACTIONS(27),
    [sym_unquoted_string_literal] = ACTIONS(29),
    [sym_dquoted_string_literal] = ACTIONS(29),
    [sym_squoted_string_literal] = ACTIONS(29),
  },
  [STATE(14)] = {
    [sym_expression] = STATE(54),
    [sym_parenthesis_expression] = STATE(40),
    [sym_binary_expression] = STATE(40),
    [sym_add_expression] = STATE(41),
    [sym_function_call] = STATE(40),
    [sym_string_literal] = STATE(40),
    [anon_sym_LPAREN] = ACTIONS(23),
    [sym_identifier] = ACTIONS(27),
    [sym_unquoted_string_literal] = ACTIONS(29),
    [sym_dquoted_string_literal] = ACTIONS(29),
    [sym_squoted_string_literal] = ACTIONS(29),
  },
  [STATE(15)] = {
    [sym_expression] = STATE(34),
    [sym_parenthesis_expression] = STATE(31),
    [sym_binary_expression] = STATE(31),
    [sym_add_expression] = STATE(33),
    [sym_function_call] = STATE(31),
    [sym_string_literal] = STATE(31),
    [anon_sym_LPAREN] = ACTIONS(41),
    [sym_identifier] = ACTIONS(43),
    [sym_unquoted_string_literal] = ACTIONS(45),
    [sym_dquoted_string_literal] = ACTIONS(45),
    [sym_squoted_string_literal] = ACTIONS(45),
  },
  [STATE(16)] = {
    [sym_expression] = STATE(45),
    [sym_parenthesis_expression] = STATE(40),
    [sym_binary_expression] = STATE(40),
    [sym_add_expression] = STATE(41),
    [sym_function_call] = STATE(40),
    [sym_string_literal] = STATE(40),
    [anon_sym_LPAREN] = ACTIONS(23),
    [sym_identifier] = ACTIONS(27),
    [sym_unquoted_string_literal] = ACTIONS(29),
    [sym_dquoted_string_literal] = ACTIONS(29),
    [sym_squoted_string_literal] = ACTIONS(29),
  },
  [STATE(17)] = {
    [sym_expression] = STATE(30),
    [sym_parenthesis_expression] = STATE(40),
    [sym_binary_expression] = STATE(40),
    [sym_add_expression] = STATE(41),
    [sym_function_call] = STATE(40),
    [sym_string_literal] = STATE(40),
    [anon_sym_LPAREN] = ACTIONS(23),
    [sym_identifier] = ACTIONS(27),
    [sym_unquoted_string_literal] = ACTIONS(29),
    [sym_dquoted_string_literal] = ACTIONS(29),
    [sym_squoted_string_literal] = ACTIONS(29),
  },
  [STATE(18)] = {
    [sym_expression] = STATE(53),
    [sym_parenthesis_expression] = STATE(40),
    [sym_binary_expression] = STATE(40),
    [sym_add_expression] = STATE(41),
    [sym_function_call] = STATE(40),
    [sym_string_literal] = STATE(40),
    [anon_sym_LPAREN] = ACTIONS(23),
    [sym_identifier] = ACTIONS(27),
    [sym_unquoted_string_literal] = ACTIONS(29),
    [sym_dquoted_string_literal] = ACTIONS(29),
    [sym_squoted_string_literal] = ACTIONS(29),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      sym_expression_sep,
    STATE(19), 1,
      aux_sym_multi_expression_repeat1,
    ACTIONS(52), 5,
      anon_sym_LPAREN,
      sym_identifier,
      sym_unquoted_string_literal,
      sym_dquoted_string_literal,
      sym_squoted_string_literal,
  [17] = 3,
    ACTIONS(54), 1,
      sym_expression_sep,
    STATE(20), 1,
      aux_sym_multi_expression_repeat1,
    ACTIONS(52), 5,
      anon_sym_LPAREN,
      sym_identifier,
      sym_unquoted_string_literal,
      sym_dquoted_string_literal,
      sym_squoted_string_literal,
  [31] = 5,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      sym_expression_sep,
    ACTIONS(61), 1,
      anon_sym_PLUS,
    STATE(4), 1,
      aux_sym_multi_expression_repeat1,
    STATE(27), 1,
      aux_sym_multi_expression_repeat2,
  [47] = 5,
    ACTIONS(61), 1,
      anon_sym_PLUS,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      sym_expression_sep,
    STATE(2), 1,
      aux_sym_multi_expression_repeat1,
    STATE(23), 1,
      aux_sym_multi_expression_repeat2,
  [63] = 4,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 1,
      sym_expression_sep,
    STATE(3), 1,
      aux_sym_multi_expression_repeat1,
    STATE(26), 1,
      aux_sym_multi_expression_repeat2,
  [76] = 3,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_PLUS,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      sym_expression_sep,
  [87] = 4,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    ACTIONS(79), 1,
      anon_sym_PLUS,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_function_call_repeat1,
  [100] = 4,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 1,
      sym_expression_sep,
    STATE(7), 1,
      aux_sym_multi_expression_repeat1,
    STATE(26), 1,
      aux_sym_multi_expression_repeat2,
  [113] = 4,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 1,
      sym_expression_sep,
    STATE(5), 1,
      aux_sym_multi_expression_repeat1,
    STATE(26), 1,
      aux_sym_multi_expression_repeat2,
  [126] = 4,
    ACTIONS(79), 1,
      anon_sym_PLUS,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_function_call_repeat1,
  [139] = 2,
    ACTIONS(96), 1,
      anon_sym_LPAREN,
    ACTIONS(71), 3,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [148] = 2,
    ACTIONS(79), 1,
      anon_sym_PLUS,
    ACTIONS(98), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [156] = 2,
    ACTIONS(75), 1,
      anon_sym_PLUS,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      sym_expression_sep,
  [164] = 2,
    ACTIONS(102), 1,
      anon_sym_PLUS,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      sym_expression_sep,
  [172] = 2,
    ACTIONS(106), 1,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      sym_expression_sep,
  [180] = 2,
    ACTIONS(110), 1,
      anon_sym_PLUS,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym_expression_sep,
  [188] = 3,
    ACTIONS(98), 1,
      anon_sym_RPAREN,
    ACTIONS(112), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_function_call_repeat1,
  [198] = 2,
    ACTIONS(117), 1,
      anon_sym_PLUS,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      sym_expression_sep,
  [206] = 2,
    ACTIONS(61), 1,
      anon_sym_PLUS,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      sym_expression_sep,
  [214] = 2,
    ACTIONS(123), 1,
      anon_sym_PLUS,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      sym_expression_sep,
  [222] = 1,
    ACTIONS(121), 3,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [228] = 1,
    ACTIONS(71), 3,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [234] = 1,
    ACTIONS(104), 3,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [240] = 2,
    ACTIONS(127), 1,
      anon_sym_PLUS,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      sym_expression_sep,
  [248] = 1,
    ACTIONS(125), 3,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [254] = 1,
    ACTIONS(129), 3,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [260] = 1,
    ACTIONS(108), 3,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [266] = 1,
    ACTIONS(131), 3,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [272] = 1,
    ACTIONS(100), 3,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [278] = 1,
    ACTIONS(115), 3,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [284] = 2,
    ACTIONS(133), 1,
      anon_sym_PLUS,
    ACTIONS(131), 2,
      ts_builtin_sym_end,
      sym_expression_sep,
  [292] = 2,
    ACTIONS(135), 1,
      anon_sym_PLUS,
    ACTIONS(129), 2,
      ts_builtin_sym_end,
      sym_expression_sep,
  [300] = 3,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    ACTIONS(137), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_function_call_repeat1,
  [310] = 3,
    ACTIONS(25), 1,
      anon_sym_RPAREN,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_function_call_repeat1,
  [320] = 2,
    ACTIONS(79), 1,
      anon_sym_PLUS,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
  [327] = 2,
    ACTIONS(79), 1,
      anon_sym_PLUS,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
  [334] = 1,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
  [338] = 1,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(19)] = 0,
  [SMALL_STATE(20)] = 17,
  [SMALL_STATE(21)] = 31,
  [SMALL_STATE(22)] = 47,
  [SMALL_STATE(23)] = 63,
  [SMALL_STATE(24)] = 76,
  [SMALL_STATE(25)] = 87,
  [SMALL_STATE(26)] = 100,
  [SMALL_STATE(27)] = 113,
  [SMALL_STATE(28)] = 126,
  [SMALL_STATE(29)] = 139,
  [SMALL_STATE(30)] = 148,
  [SMALL_STATE(31)] = 156,
  [SMALL_STATE(32)] = 164,
  [SMALL_STATE(33)] = 172,
  [SMALL_STATE(34)] = 180,
  [SMALL_STATE(35)] = 188,
  [SMALL_STATE(36)] = 198,
  [SMALL_STATE(37)] = 206,
  [SMALL_STATE(38)] = 214,
  [SMALL_STATE(39)] = 222,
  [SMALL_STATE(40)] = 228,
  [SMALL_STATE(41)] = 234,
  [SMALL_STATE(42)] = 240,
  [SMALL_STATE(43)] = 248,
  [SMALL_STATE(44)] = 254,
  [SMALL_STATE(45)] = 260,
  [SMALL_STATE(46)] = 266,
  [SMALL_STATE(47)] = 272,
  [SMALL_STATE(48)] = 278,
  [SMALL_STATE(49)] = 284,
  [SMALL_STATE(50)] = 292,
  [SMALL_STATE(51)] = 300,
  [SMALL_STATE(52)] = 310,
  [SMALL_STATE(53)] = 320,
  [SMALL_STATE(54)] = 327,
  [SMALL_STATE(55)] = 334,
  [SMALL_STATE(56)] = 338,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_expression, 2, 0, 1),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_expression, 3, 0, 2),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_expression, 3, 0, 3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_expression, 4, 0, 6),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multi_expression_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multi_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_multi_expression_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multi_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_expression, 2, 0, 3),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_expression, 1, 0, 1),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_expression, 2, 0, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multi_expression_repeat2, 2, 0, 5),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multi_expression_repeat2, 2, 0, 5), SHIFT_REPEAT(7),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_expression, 3, 0, 6),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_expression, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_expression, 3, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 6, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 6, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multi_expression_repeat2, 2, 0, 4),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesis_expression, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesis_expression, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [145] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lcdcdsl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lcdcdsl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
