/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_PLUS = 3,
  anon_sym_COMMA = 4,
  sym_identifier = 5,
  sym_unquoted_string_literal = 6,
  sym_dquoted_string_literal = 7,
  sym_squoted_string_literal = 8,
  sym_source_file = 9,
  sym_expression = 10,
  sym_parenthesis_expression = 11,
  sym_binary_expression = 12,
  sym_add_expression = 13,
  sym_function_call = 14,
  sym_string_literal = 15,
  aux_sym_function_call_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PLUS] = "+",
  [anon_sym_COMMA] = ",",
  [sym_identifier] = "identifier",
  [sym_unquoted_string_literal] = "unquoted_string_literal",
  [sym_dquoted_string_literal] = "dquoted_string_literal",
  [sym_squoted_string_literal] = "squoted_string_literal",
  [sym_source_file] = "source_file",
  [sym_expression] = "expression",
  [sym_parenthesis_expression] = "parenthesis_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_add_expression] = "add_expression",
  [sym_function_call] = "function_call",
  [sym_string_literal] = "string_literal",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_identifier] = sym_identifier,
  [sym_unquoted_string_literal] = sym_unquoted_string_literal,
  [sym_dquoted_string_literal] = sym_dquoted_string_literal,
  [sym_squoted_string_literal] = sym_squoted_string_literal,
  [sym_source_file] = sym_source_file,
  [sym_expression] = sym_expression,
  [sym_parenthesis_expression] = sym_parenthesis_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_add_expression] = sym_add_expression,
  [sym_function_call] = sym_function_call,
  [sym_string_literal] = sym_string_literal,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_dquoted_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_squoted_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_parenthesis_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_add_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_expression,
  sym_string_literal,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_expression] = {.index = 0, .length = 5},
  [sym_string_literal] = {.index = 5, .length = 3},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_binary_expression,
    sym_function_call,
    sym_identifier,
    sym_parenthesis_expression,
    sym_string_literal,
  [5] =
    sym_dquoted_string_literal,
    sym_squoted_string_literal,
    sym_unquoted_string_literal,
};

static const TSCharacterRange sym_unquoted_string_literal_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '#'}, {'%', '&'}, {'*', '*'}, {'-', 'z'}, {'|', '|'},
  {'~', 0x17e}, {0x180, 0x2129}, {0x212b, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 1,
        '$', 4,
        '\'', 2,
        '(', 9,
        ')', 10,
        '+', 11,
        ',', 12,
        '\\', 3,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"' ||
          lookahead == '$' ||
          ('\'' <= lookahead && lookahead <= ')') ||
          lookahead == '+' ||
          lookahead == ',' ||
          lookahead == '\\' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(17);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(1);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(2);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == '@') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == '@') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_unquoted_string_literal);
      if (lookahead == '\\') ADVANCE(3);
      if ((!eof && set_contains(sym_unquoted_string_literal_character_set_1, 11, lookahead))) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_dquoted_string_literal);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_squoted_string_literal);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_unquoted_string_literal] = ACTIONS(1),
    [sym_dquoted_string_literal] = ACTIONS(1),
    [sym_squoted_string_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(24),
    [sym_expression] = STATE(22),
    [sym_parenthesis_expression] = STATE(10),
    [sym_binary_expression] = STATE(10),
    [sym_add_expression] = STATE(11),
    [sym_function_call] = STATE(10),
    [sym_string_literal] = STATE(10),
    [anon_sym_LPAREN] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_unquoted_string_literal] = ACTIONS(7),
    [sym_dquoted_string_literal] = ACTIONS(7),
    [sym_squoted_string_literal] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_expression] = STATE(15),
    [sym_parenthesis_expression] = STATE(10),
    [sym_binary_expression] = STATE(10),
    [sym_add_expression] = STATE(11),
    [sym_function_call] = STATE(10),
    [sym_string_literal] = STATE(10),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_RPAREN] = ACTIONS(9),
    [sym_identifier] = ACTIONS(5),
    [sym_unquoted_string_literal] = ACTIONS(7),
    [sym_dquoted_string_literal] = ACTIONS(7),
    [sym_squoted_string_literal] = ACTIONS(7),
  },
  [STATE(3)] = {
    [sym_expression] = STATE(20),
    [sym_parenthesis_expression] = STATE(10),
    [sym_binary_expression] = STATE(10),
    [sym_add_expression] = STATE(11),
    [sym_function_call] = STATE(10),
    [sym_string_literal] = STATE(10),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_RPAREN] = ACTIONS(11),
    [sym_identifier] = ACTIONS(5),
    [sym_unquoted_string_literal] = ACTIONS(7),
    [sym_dquoted_string_literal] = ACTIONS(7),
    [sym_squoted_string_literal] = ACTIONS(7),
  },
  [STATE(4)] = {
    [sym_expression] = STATE(20),
    [sym_parenthesis_expression] = STATE(10),
    [sym_binary_expression] = STATE(10),
    [sym_add_expression] = STATE(11),
    [sym_function_call] = STATE(10),
    [sym_string_literal] = STATE(10),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_RPAREN] = ACTIONS(13),
    [sym_identifier] = ACTIONS(5),
    [sym_unquoted_string_literal] = ACTIONS(7),
    [sym_dquoted_string_literal] = ACTIONS(7),
    [sym_squoted_string_literal] = ACTIONS(7),
  },
  [STATE(5)] = {
    [sym_expression] = STATE(23),
    [sym_parenthesis_expression] = STATE(10),
    [sym_binary_expression] = STATE(10),
    [sym_add_expression] = STATE(11),
    [sym_function_call] = STATE(10),
    [sym_string_literal] = STATE(10),
    [anon_sym_LPAREN] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_unquoted_string_literal] = ACTIONS(7),
    [sym_dquoted_string_literal] = ACTIONS(7),
    [sym_squoted_string_literal] = ACTIONS(7),
  },
  [STATE(6)] = {
    [sym_expression] = STATE(12),
    [sym_parenthesis_expression] = STATE(10),
    [sym_binary_expression] = STATE(10),
    [sym_add_expression] = STATE(11),
    [sym_function_call] = STATE(10),
    [sym_string_literal] = STATE(10),
    [anon_sym_LPAREN] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_unquoted_string_literal] = ACTIONS(7),
    [sym_dquoted_string_literal] = ACTIONS(7),
    [sym_squoted_string_literal] = ACTIONS(7),
  },
  [STATE(7)] = {
    [sym_expression] = STATE(20),
    [sym_parenthesis_expression] = STATE(10),
    [sym_binary_expression] = STATE(10),
    [sym_add_expression] = STATE(11),
    [sym_function_call] = STATE(10),
    [sym_string_literal] = STATE(10),
    [anon_sym_LPAREN] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_unquoted_string_literal] = ACTIONS(7),
    [sym_dquoted_string_literal] = ACTIONS(7),
    [sym_squoted_string_literal] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [10] = 1,
    ACTIONS(19), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [17] = 1,
    ACTIONS(15), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [24] = 1,
    ACTIONS(21), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [31] = 1,
    ACTIONS(23), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [38] = 1,
    ACTIONS(25), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [45] = 1,
    ACTIONS(27), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [52] = 4,
    ACTIONS(29), 1,
      anon_sym_RPAREN,
    ACTIONS(31), 1,
      anon_sym_PLUS,
    ACTIONS(33), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      aux_sym_function_call_repeat1,
  [65] = 1,
    ACTIONS(35), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [72] = 1,
    ACTIONS(37), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [79] = 1,
    ACTIONS(39), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_COMMA,
  [86] = 3,
    ACTIONS(11), 1,
      anon_sym_RPAREN,
    ACTIONS(41), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_function_call_repeat1,
  [96] = 2,
    ACTIONS(31), 1,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [104] = 3,
    ACTIONS(43), 1,
      anon_sym_RPAREN,
    ACTIONS(45), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_function_call_repeat1,
  [114] = 2,
    ACTIONS(31), 1,
      anon_sym_PLUS,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
  [121] = 2,
    ACTIONS(31), 1,
      anon_sym_PLUS,
    ACTIONS(50), 1,
      anon_sym_RPAREN,
  [128] = 1,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 10,
  [SMALL_STATE(10)] = 17,
  [SMALL_STATE(11)] = 24,
  [SMALL_STATE(12)] = 31,
  [SMALL_STATE(13)] = 38,
  [SMALL_STATE(14)] = 45,
  [SMALL_STATE(15)] = 52,
  [SMALL_STATE(16)] = 65,
  [SMALL_STATE(17)] = 72,
  [SMALL_STATE(18)] = 79,
  [SMALL_STATE(19)] = 86,
  [SMALL_STATE(20)] = 96,
  [SMALL_STATE(21)] = 104,
  [SMALL_STATE(22)] = 114,
  [SMALL_STATE(23)] = 121,
  [SMALL_STATE(24)] = 128,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_expression, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 6, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesis_expression, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [52] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lcdcdsl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lcdcdsl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
