[package]
name = "langcities-signal"
version.workspace = true
authors.workspace = true
edition.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true

[features]
default = ["signal-hook"]
signal-hook = ["dep:signal-hook", "dep:signal-hook-tokio"]

[dependencies]
tokio = { version = "1.53", features = ["signal"] }
tokio-stream = { version = "0.1.19", features = ["sync"] }
futures = { version = "0.3.34" }

[target.'cfg(unix)'.dependencies]
signal-hook = { version = "0.4.5", optional = true }
signal-hook-tokio = { version = "0.4.0", optional = true, features = ["futures-v0_3"] }
