[package]
name = "langcities-jwt"
version.workspace = true
authors.workspace = true
edition.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
chrono = "0.4.45"
clap = { version = "4.6.6", features = ["derive", "string"] }
figment = { version = "0.10.19", features = ["env"] }
jsonwebtoken = "11.0.0"
langcities-common = { path = "../langcities-common" }
langcities-config = { path = "../langcities-config" }
serde = { version = "1.0.229", features = ["derive"] }
