//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "dc_users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub auth_user_id: i64,
    #[sea_orm(has_many)]
    pub vernaculars: HasMany<super::vernaculars::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
