//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "entry_field_dependencies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub child_entry_field_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub parent_kind: i16,
    #[sea_orm(primary_key, auto_increment = false)]
    pub parent_id: i64,
    #[sea_orm(
        belongs_to,
        from = "child_entry_field_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub entry_fields: BelongsTo<super::entry_fields::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
