//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "entry_field_job_attempts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub job_id: i64,
    pub worker_id: i64,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub finished_at: Option<DateTimeUtc>,
    pub expires_at: DateTimeUtc,
    #[sea_orm(column_type = "Text", nullable)]
    pub calculated_value: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "job_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    pub entry_field_jobs: BelongsTo<super::entry_field_jobs::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
