//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "entry_field_jobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub entry_field_id: i64,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub expires_at: DateTimeUtc,
    pub n_attempts: i64,
    #[sea_orm(has_many)]
    pub entry_field_job_attempts: HasMany<super::entry_field_job_attempts::Entity>,
    #[sea_orm(
        belongs_to,
        from = "entry_field_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    pub entry_fields: BelongsTo<super::entry_fields::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
