//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "entry_fields")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub entry_id: i64,
    pub slug: String,
    pub r#override: String,
    pub dirty_value: String,
    pub clean_value: String,
    pub updated_at: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "entry_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub entries: BelongsTo<super::entries::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
