//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "entries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub vernacular_id: i64,
    pub index: i64,
    pub created_at: DateTimeUtc,
    #[sea_orm(has_many)]
    pub entry_fields: HasMany<super::entry_fields::Entity>,
    #[sea_orm(
        belongs_to,
        from = "vernacular_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub vernaculars: BelongsTo<super::vernaculars::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
