//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "vernaculars")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub slug: String,
    pub name: String,
    pub updated_at: DateTimeUtc,
    pub created_at: DateTimeUtc,
    pub owner_id: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "owner_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub dc_users: BelongsTo<Option<super::dc_users::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
